---
- hosts: all
  tasks:
  - name: update cache for Ubuntu
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: update cache for Centos
    yum:
      update_cache: yes
    when: ansible_distribution == "CentOS"
  - name: install apache on Ubuntu
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache on Centos
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS"

